using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class GameMenu : MonoBehaviour
{

    public GameObject pauseMenu;


    private void Start()
    {
        ResumeGame();

    }

    private void Update()
    {
        if(Input.GetKeyDown(KeyCode.Escape) == true)
           
        {
            if(Time.timeScale == 0.0f)
            {
                ResumeGame();
            }
            else
            
            {
                PauseGame();
            }

        }



    }


    private void PauseGame()
    {
        pauseMenu.SetActive(true);
        Time.timeScale = 0.0f;
    }

    private void ResumeGame()
    {
        pauseMenu.SetActive(false);
        Time.timeScale = 1.0f;
    }



    public void OnResumeClicked()
    {
        ResumeGame();
    }

    
    public void OnBackToMenuClicked()
    {
        SceneManager.LoadScene("Level_02");
    }
}
